; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32 @ ^6.8.1
board = esp32dev
board_build.filesystem = littlefs
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.partitions = min_spiffs.csv
build_flags = -DNO_GLOBAL_EEPROM -DDEBUG_EEPROM32_ROTATE_PORT=Serial -DI2C_BUFFER_LENGTH=255 -g -std=c++11 -D_GLIBCXX_USE_C99 -fno-rtti -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_VERBOSE
;-DUSE_SERIAL
extra_scripts = pre:firmware_file_name.py
custom_prog_version = 1.0.3
lib_deps = Wire
           AsyncTCP
           Adafruit Unified Sensor
           https://github.com/me-no-dev/ESPAsyncWebServer.git#master
           https://github.com/s00500/ESPUI.git
           https://github.com/AOG-silrep/AsyncElegantOTA.git#master
           bblanchon/ArduinoJson@^6.7.0
           coryjfowler/mcp_can@^1.5.1
