name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: pio run
    - name: Zip Folder
      run: zip -D firmware.zip .pio/build/featheresp32/firmware.bin .pio/build/featheresp32/partitions.bin
    - name: Update release if master
      uses: johnwbyrd/update-release@v1.0.0
      if: success() && github.ref == 'refs/heads/master'
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: firmware.zip
        prerelease: true
        release: latest
        message: This is the lastest, automatically built version. Use with caution!
        tag: latest
    - name: Update release if tag
      uses: johnwbyrd/update-release@v1.0.0
      if: success() && startsWith(github.ref, 'refs/tags/')
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: firmware.zip
        prerelease: false 
        message: This is a regular built version. Should be safe to use.
